server:
  bind: "127.0.0.1:8080"

cache:
  data_dir: "./data"
  media_ttl_minutes: 360
  media_max_megabytes: 10240
  disconnect_behavior: "delay_cancel"
  disconnect_grace_seconds: 15

metadata:
  refresh_interval_hours: 24
  refresh_recent_grace_minutes: 60

downloads:
  max_concurrent: 3

auth:
  enabled: false

users:
  - name: "derek"
    services:
      - kind: "soundcloud"
        account: "dereknet"
        profile_url: "https://soundcloud.com/dereknet"
        feeds:
          - profile
          - likes 
      - kind: "soundcloud"
        account: "NTS"
        profile_url: "https://soundcloud.com/user-202286394-991268468"
        feeds:
          - profile

  # - name: "NTS"
  #   services:
  #     - kind: "soundcloud"
  #       account: "NTS Latest"
  #       profile_url: "https://soundcloud.com/user-202286394-991268468"
  #       feeds:
  #         - profile
