use std::collections::BTreeMap;

use chrono::{DateTime, Utc};
use rss::extension::itunes::ITunesItemExtension;
use rss::extension::{Extension, ExtensionMap};
use rss::{ChannelBuilder, EnclosureBuilder, GuidBuilder, ItemBuilder};

use crate::config::{ServiceConfig, SoundCloudFeedKind};
use crate::media::FeedItem;
use crate::metadata;

pub fn render_feed(
    base_url: &str,
    user: &str,
    service: &ServiceConfig,
    feed: SoundCloudFeedKind,
    items: &[FeedItem],
    last_successful_refresh: DateTime<Utc>,
) -> anyhow::Result<String> {
    let feed_path = crate::html::feed_path(user, service.kind.as_path(), &service.name, feed);
    let channel_link = format!("{base_url}{feed_path}");
    let source_url = feed.source_url(service);
    let title = format!(
        "{} {} {}",
        service.name,
        service.kind.as_path(),
        feed.label()
    );

    let rss_items: Vec<rss::Item> = items
        .iter()
        .map(|item| {
            let media_url = format!(
                "{base_url}/users/{}/{}/{}/items/{}/audio.m4a",
                urlencoding::encode(user),
                urlencoding::encode(service.kind.as_path()),
                urlencoding::encode(&service.name),
                urlencoding::encode(&item.id)
            );
            let enclosure = EnclosureBuilder::default()
                .url(media_url)
                .mime_type("audio/mp4".to_string())
                .length(item.content_length.unwrap_or(0).to_string())
                .build();

            let mut builder = ItemBuilder::default();
            if let Some(thumbnail_url) = &item.thumbnail_url {
                builder.extensions(item_artwork_extensions(thumbnail_url));
                builder.itunes_ext(ITunesItemExtension {
                    image: Some(thumbnail_url.clone()),
                    ..ITunesItemExtension::default()
                });
            }

            builder
                .title(Some(item.title.clone()))
                .link(Some(item.webpage_url.clone()))
                .description(item.description.clone())
                .pub_date(item.published_at.map(rfc2822))
                .guid(Some(
                    GuidBuilder::default()
                        .value(item.id.clone())
                        .permalink(false)
                        .build(),
                ))
                .enclosure(Some(enclosure))
                .build()
        })
        .collect();

    let channel = ChannelBuilder::default()
        .title(title)
        .link(source_url)
        .description(format!("Generated by yt-dlp-feed for {channel_link}"))
        .last_build_date(rfc2822(last_successful_refresh))
        .generator(Some("yt-dlp-feed".to_string()))
        .namespaces(metadata::namespace_map())
        .extensions(channel_extensions(&channel_link))
        .items(rss_items)
        .build();

    Ok(channel.to_string())
}

fn rfc2822(datetime: DateTime<Utc>) -> String {
    datetime.to_rfc2822()
}

fn channel_extensions(channel_link: &str) -> ExtensionMap {
    let mut map = ExtensionMap::new();
    let mut attrs = BTreeMap::new();
    attrs.insert("href".to_string(), channel_link.to_string());
    attrs.insert("rel".to_string(), "self".to_string());
    attrs.insert("type".to_string(), "application/rss+xml".to_string());
    map.entry("atom".to_string())
        .or_default()
        .entry("link".to_string())
        .or_default()
        .push(Extension {
            name: "atom:link".to_string(),
            attrs,
            ..Extension::default()
        });
    map
}

fn item_artwork_extensions(thumbnail_url: &str) -> ExtensionMap {
    let mut map = ExtensionMap::new();
    let mut attrs = BTreeMap::new();
    attrs.insert("url".to_string(), thumbnail_url.to_string());
    map.entry("media".to_string())
        .or_default()
        .entry("thumbnail".to_string())
        .or_default()
        .push(Extension {
            name: "media:thumbnail".to_string(),
            attrs,
            ..Extension::default()
        });
    map
}
