use chrono::{DateTime, Utc};
use rss::{ChannelBuilder, EnclosureBuilder, GuidBuilder, ItemBuilder};

use crate::config::{ServiceConfig, SoundCloudFeedKind};
use crate::media::FeedItem;

pub fn render_feed(
    base_url: &str,
    user: &str,
    service: &ServiceConfig,
    feed: SoundCloudFeedKind,
    items: &[FeedItem],
) -> anyhow::Result<String> {
    let feed_path = crate::html::feed_path(user, service.kind.as_path(), &service.account, feed);
    let channel_link = format!("{base_url}{feed_path}");
    let source_url = feed.source_url(service);
    let title = format!(
        "{} {} {}",
        service.account,
        service.kind.as_path(),
        feed.label()
    );

    let rss_items: Vec<rss::Item> = items
        .iter()
        .map(|item| {
            let media_url = format!(
                "{base_url}/users/{}/{}/{}/items/{}/audio.m4a",
                urlencoding::encode(user),
                urlencoding::encode(service.kind.as_path()),
                urlencoding::encode(&service.account),
                urlencoding::encode(&item.id)
            );
            let enclosure = EnclosureBuilder::default()
                .url(media_url)
                .mime_type("audio/mp4".to_string())
                .length(item.content_length.unwrap_or(0).to_string())
                .build();

            ItemBuilder::default()
                .title(Some(item.title.clone()))
                .link(Some(item.webpage_url.clone()))
                .description(item.description.clone())
                .pub_date(item.published_at.map(rfc2822))
                .guid(Some(
                    GuidBuilder::default()
                        .value(item.id.clone())
                        .permalink(false)
                        .build(),
                ))
                .enclosure(Some(enclosure))
                .build()
        })
        .collect();

    let channel = ChannelBuilder::default()
        .title(title)
        .link(source_url)
        .description(format!("Generated by yt-dlp-feed for {channel_link}"))
        .items(rss_items)
        .build();

    Ok(channel.to_string())
}

fn rfc2822(datetime: DateTime<Utc>) -> String {
    datetime.to_rfc2822()
}
